### ISSUE TITLE
TODO - init

### ISSUE THREAD

**Issue by zuevval** [braille-systems/tiles-recognition#1]
- [ ] choose CI
- [ ] set up CI

**Comment by penguin-boxx** [comment]
What does CI mean in this context?

**Comment by zuevval** [comment]
> What does CI mean in this context?

unit tests

**Comment by penguin-boxx** [comment]
O, not so quickly :) But we will also estimate accuracy on the validation

**Comment by zuevval** [comment]
if you choose TDD, then you should write tests sooner, perhaps even before collecting data.

But it's up to you, after all.
