### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by penguin-boxx** [braille-systems/tiles-recognition#3]
Images (format?, size?) and label files in CSV (`object (tile) number`, `bb x`, `bb y`, `label`).

On each image: word placed horizontally, other positions will be generated at augmentation.

Variate:
- use all possible letters
- words of different length
- position of word on the image
- lonely tiles and shorter words randomly on the same image
- different distance from the camera to tiles

**Comment by penguin-boxx** [comment]
What size of dataset do we need before augmentation?

Есть еще такое мнение от про:
```
По конкретным моментам реализации two-shot вам и не нужен, и долго
Количество картинок, т.к. хорошо формализована задача большое не нужно
По сути - любой готовый пайплайн отработает
Вам скорее на счет разметки нужно задуматься
Если правильно все сделать - SSD/YOLO на паре сотен сэмплов решит задачу довольно хорошо
```

**Comment by penguin-boxx** [comment]
I think image format does not matter, PILLOW will help.

**Comment by penguin-boxx** [comment]
Also, they can be with high resolution as from cam, but with an aspect ratio nothing is clear

**Comment by zuevval** [comment]
> What size of dataset do we need before augmentation?

Why do you ask *me*? I may tell you how many pictures I can make: in theory, generally speaking, I can make an unlimited amount using four to five different Android devices. Say, 1000 in total (it might be somewhat more difficult to label them, though).

Let's first formalize requirements for dataset: must they capture a single tile each or a sequence? must they be labeled and how if yes? are there special requirements for lights?

**Comment by penguin-boxx** [comment]
@zuevval it's rhetorical questions :) To think about in the future)

**Comment by penguin-boxx** [comment]
Also, we need plans to automatize the process. Some more comments from an expert:
```
Неплохо было бы сделать кучу разных фотографий и медленными около алгоритмическим методами разметить
Сделать аугментацию
И на этом обучать быстрый детектор, который можно в телефоне упаковать
В opencv есть SIFT, но он платный
На них можно легко разметку сделать автоматизированную
```
