### ISSUE TITLE
SSD approach

### ISSUE THREAD

**Issue by penguin-boxx** [braille-systems/tiles-recognition#4]
- [paper](https://arxiv.org/pdf/1512.02325.pdf)
- https://medium.com/@jonathan_hui/ssd-object-detection-single-shot-multibox-detector-for-real-time-processing-9bd8deac0e06
- https://lilianweng.github.io/lil-log/2018/12/27/object-detection-part-4.html
- http://zoey4ai.com/2018/05/12/deep-learning-object-detection/

**Comment by penguin-boxx** [comment]
![1*up-gIJ9rPkHXUGRoqWuULQ](https://user-images.githubusercontent.com/25281147/78893066-45da8d00-7a73-11ea-9e68-a314f2647f4f.jpeg)

**Comment by zuevval** [comment]
oh, my Lord, *this* looks pretty scientific. Wish I could make something alike one day.

**Comment by KoT9R** [comment]
https://pytorch.org/hub/nvidia_deeplearningexamples_ssd/
Есть же в pytorch реализация SSD, или нам нужно свою написать, чтобы адаптировать под мобилки?

**Comment by penguin-boxx** [comment]
> https://pytorch.org/hub/nvidia_deeplearningexamples_ssd/
> Есть же в pytorch реализация SSD, или нам нужно свою написать, чтобы адаптировать под мобилки?

Не, все супер, я ее не нашел просто. Нужно ли руками переписывать, я потом спрошу, а начинать нужно точно с готовой.
